name: Bun Compatibility

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  os:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        bun-version: [1.0.0, 1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Upload mysqlmsn directory
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: bun-${{ matrix.bun-version }}
          path: /tmp/mysqlmsn
          compression-level: 9