name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci-node:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        # We only support Node.js 16 and newer
        node-version: [16.6.0, 16.x, 17.0.0, 17.x, 18.x, 19.x, 20.x, 21.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Upload test dbs (Linux/macOS)
        if: ${{ runner.os != 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: Databases-${{ matrix.os }}-node${{ matrix.node-version }}
          path: /tmp/dbs

      - name: Upload test dbs (Windows)
        if: ${{ runner.os == 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: Databases-${{ matrix.os }}-node${{ matrix.node-version }}
          path: "C:\\Users\\RUNNER~1\\dbs"

  ci-bun:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        bun-version: [1.1.22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install packages
        run: bun install

      - name: Run tests
        run: bun run test:ci

      - name: Upload test dbs (Linux/macOS)
        if: ${{ runner.os != 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: Databases-${{ matrix.os }}-bun
          path: /tmp/dbs

      - name: Upload test dbs (Windows)
        if: ${{ runner.os == 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: Databases-${{ matrix.os }}-bun
          path: "C:\\Users\\RUNNER~1\\dbs"

  test-node:
    runs-on: ${{ matrix.os }}
    needs: ci-node

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm test

  test-bun:
    runs-on: ${{ matrix.os }}
    needs: ci-bun

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun 1.1.22
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.22

      - name: Install packages
        run: bun install

      - name: Run tests
        run: bun run test

  stress-node:
    runs-on: ${{ matrix.os }}
    needs: test-node

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        if: ${{ runner.os == 'Linux' }}
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Free Disk Space (macOS)
        if: ${{ runner.os == 'macOS' }}
        working-directory: /Applications
        run: |
          sudo find . -name Xcode\*.app -delete
          sudo rm -rf /Users/runner/Library/Android

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run stress

      - name: Upload test dbs (Linux/macOS)
        if: ${{ runner.os != 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: StressTest-Databases-${{ matrix.os }}-node
          path: |
            /tmp/dbs
            !/temp/dbs/*/*.sock

      - name: Upload test dbs (Windows)
        if: ${{ runner.os == 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: StressTest-Databases-${{ matrix.os }}-node
          path: "C:\\Users\\RUNNER~1\\dbs"

  stress-bun:
    runs-on: ${{ matrix.os }}
    needs: test-bun

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        if: ${{ runner.os == 'Linux' }}
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Free Disk Space (macOS)
        if: ${{ runner.os == 'macOS' }}
        working-directory: /Applications
        run: sudo find . -name Xcode\*.app -delete

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun 1.1.22
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.22

      - name: Install packages
        run: bun install

      - name: Run tests
        run: bun run stress

      - name: Upload test dbs (Linux/macOS)
        if: ${{ runner.os != 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: StressTest-Databases-${{ matrix.os }}-bun
          path: |
            /tmp/dbs
            !/temp/dbs/*/*.sock

      - name: Upload test dbs (Windows)
        if: ${{ runner.os == 'Windows' && failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: StressTest-Databases-${{ matrix.os }}-bun
          path: "C:\\Users\\RUNNER~1\\dbs"

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        run: sudo dnf install nodejs -y

      - name: Install required libraries
        run: sudo dnf install libaio numactl -y

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test