name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04]
        # We only support Node.js 16 and newer
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x, 21.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Create dbs folder
        run: mkdir dbs
      - name: Run tests
        run: npm test
      - name: Upload test dbs
        uses: actions/upload-artifact@v4
        with:
          name: Databases-${{ matrix.os }}-node${{ matrix.node-version }}
          path: ${{ github.workspace }}/dbs