name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Move MySQLMSN directory for GitHub Actions upload
        if: ${{ failure() }}
        env:
          MOVE_MYSQLMSN_TO: /tmp/mysqlmsn
        run: npx ts-node tests/ci/DirMoveGitHubActions.ts

      - name: Upload mysqlmsn directory (Not Windows)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: ci-mysqlmsn-dir
          path: /tmp/mysqlmsn
          compression-level: 9