name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node LTS
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Install packages
        run: npm ci

      - name: Build code
        run: npx tsc

      - name: Run tests
        run: npm run test:ci

      - name: Move MySQLMSN directory for GitHub Actions upload
        if: ${{ failure() }}
        env:
          MOVE_MYSQLMSN_TO: /tmp/mysqlmsn
        run: node tests/ci/DirMoveGitHubActions.js

      - name: Upload mysqlmsn directory
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: ci-mysqlmsn-dir
          path: /tmp/mysqlmsn
          compression-level: 9