name: OS Compatibility

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  os:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, windows-2019, windows-2022]
        #There is no 10.0.0 at the time of writing, but since greater than characters are not allowed in GitHub Actions artifacts names, 9.0.1 - 10.0.0 will be used instead of >9.0.0
        version-requirement: ['5.7.19 - 5.7.30', '5.7.31 - 5.7.40', '5.7.41 - 5.7.44', '8.0.0 - 8.0.12', '8.0.13 - 8.0.26', '8.0.27 - 8.0.40', '8.0.41 - 9.0.0', '9.0.1 - 10.0.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Install packages
        run: npm ci

      - name: Run tests
        env:
          VERSION_REQUIREMENT: ${{ matrix.version-requirement }}
        run: npm run test:ci

      - name: Upload mysqlmsn directory (Windows)
        if: ${{ failure() && runner.os == 'Windows' }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: ${{ matrix.os }}-${{ matrix.version-requirement }}
          path: "C:\\Users\\RUNNER~1\\mysqlmsn"
          compression-level: 0

      - name: Upload mysqlmsn directory (Not Windows)
        if: ${{ failure() && runner.os != 'Windows' }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: ${{ matrix.os }}-${{ matrix.version-requirement }}
          path: /tmp/mysqlmsn
          compression-level: 0

  fedora-docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [40]
        #There is no 10.0.0 at the time of writing, but since greater than characters are not allowed in GitHub Actions artifacts names, 9.0.1 - 10.0.0 will be used instead of >9.0.0
        version-requirement: ['5.7.19 - 5.7.30', '5.7.31 - 5.7.40', '5.7.41 - 5.7.44', '8.0.0 - 8.0.12', '8.0.13 - 8.0.26', '8.0.27 - 8.0.40', '8.0.41 - 9.0.0', '9.0.1 - 10.0.0']

    container: fedora:${{ matrix.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Install required libraries
        run: sudo dnf install libaio numactl libxcrypt-compat -y

      - name: Install packages
        run: npm ci

      - name: Print available storage space
        run: df -h

      - name: Run tests
        env:
          VERSION_REQUIREMENT: ${{ matrix.version-requirement }}
        run: npm run test:ci

      - name: Upload mysqlmsn directory
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4.3.5
        with:
          name: docker-fedora-${{ matrix.version }}-${{ matrix.version-requirement }}
          path: /tmp/mysqlmsn
          compression-level: 0